"""stdio_json entrypoint for a Contract v1 field-surrogate package.

Protocol (`invocation.protocol: stdio_json`).
One JSON object on stdin then EOF; one *frame* per dispatched row on stdout.

    {"run_id": "abc", "mode": "single",
     "inputs": {"k0_W_mK": 45.0, "h_W_m2K": 60.0, "t_m": 0.003,
                "source_P_W": 12.0, "source_sigma_m": 0.007,
                "source_xc_m": 0.05, "source_yc_m": 0.05}}
 -> {"run_id": "abc", "status": "ok",
     "outputs": {"dT": [[...]], "dT_lower": [[...]], "dT_upper": [[...]],
                 "dT_max_K": 7.4, "units": "K", "grid": [64, 64]}}

`mode: "batch"` takes `inputs` as a JSON *array* and answers one frame per row,
newline-delimited, in submission order.  `mode` and `run_id` are both optional:
a bare `{"inputs": {...}}` request still answers one `status: "ok"` frame, which
is what the producer's packaging acceptance requires.

An input this model will not accept is a **valid** protocol response, not a
crash: one frame `{"run_id", "status": "error", "error": {code, message, field}}`
with `code` in `MISSING_INPUT` / `OUT_OF_RANGE` / `BAD_REQUEST`, **and exit 0**.
The exit code matters: a dispatcher reads how the process ended before it
reads the frame, so exiting nonzero here would be recorded
`nonzero_exit` / HTTP 502 instead of `model_error` / HTTP 422.  A nonzero exit is reserved for a genuine internal
failure, which is the one case where 502 is the honest answer.

The accepted envelope below (`RANGES`) is the manifest's own `inputs[].range`,
baked in at emission from the same resolved values the manifest declares, so the
range this entrypoint enforces cannot drift from the range it advertises.

`design_json` may be supplied instead of the scalars: a JSON-encoded full design
object (`{"k0":..., "h":..., "t":..., "inserts":[...], "sources":[...]}`) as
produced by the producer's design sampler.  When present it supersedes
the scalar fields, so multi-source plates and conductivity inserts -- which
Contract v1's scalar-only input vocabulary cannot type -- remain reachable.  Its
`k0`/`h`/`t` are range-checked (they map one-to-one onto declared inputs); its
`sources` are not, because a multi-source plate has no single `source_P_W` and
imposing the scalar envelope on it would reject exactly the designs the escape
hatch exists to reach.

numpy is the only third-party import.  The forward pass, the GELU and the channel
builders below are spliced verbatim out of the producer's installed source by
its package emitter, so what ships here is byte-identical to what gate FG9
(serve parity) measured.  Do not hand-edit them: any edit is an unvalidated
divergence, and it also breaks the sha256 this package's manifest pins.

Generated by the producer's package emitter 0.1.0 from its training run, model fno.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np

WEIGHTS_PATH = Path(__file__).resolve().parent / "fno_weights.npz"

# Geometry and grid of the corpus this surrogate was trained on.  A prediction is
# only meaningful on this grid: the normalisation statistics and the spectral
# modes below were fitted to it.
CONFIG = {
    "nx": 64,
    "ny": 64,
    "Lx": 0.1,
    "Ly": 0.1,
    "T_inf": 300.0
}

# Per-channel z-score statistics and the target scale, fitted on the training
# split only (the producer's normaliser fit).
NORM = {
    "x_mean": [
        1.7551326751708984,
        0.44899383187294006,
        1.8214634656906128,
        3.517259359359741,
        0.5,
        0.5
    ],
    "x_std": [
        0.3590996563434601,
        0.8866859078407288,
        0.3727407157421112,
        1.4594978094100952,
        0.2886399030685425,
        0.2886399030685425
    ],
    "y_mean": 19.568828582763672,
    "y_std": 25.634389877319336
}

N_CHANNELS = 6

# The FG3 split-conformal half-width, in kelvin, on the per-sample worst cell.
BAND_HALFWIDTH_K = 6.540130615234375

REQUIRED_SCALARS = [
    "k0_W_mK",
    "h_W_m2K",
    "t_m",
    "source_P_W",
    "source_sigma_m",
    "source_xc_m",
    "source_yc_m"
]

# The accepted envelope, copied from this package's manifest.yaml inputs[].range
# at emission. Editing it here without editing the manifest is the divergence the
# emitter exists to prevent -- the producer's own tests assert the two agree.
RANGES = {
    "k0_W_mK": [
        15.0,
        220.0
    ],
    "h_W_m2K": [
        15.0,
        300.0
    ],
    "t_m": [
        0.001,
        0.006
    ],
    "source_P_W": [
        2.0,
        25.0
    ],
    "source_sigma_m": [
        0.004,
        0.012
    ],
    "source_xc_m": [
        0.015,
        0.095
    ],
    "source_yc_m": [
        0.005000000000000001,
        0.095
    ]
}

# --------------------------------------------------------------------------- #
# Spliced verbatim from the producer's numpy forward pass and feature builders
# (release 0.1.0). This is the forward pass gate FG9 measured; do not edit it here.
# --------------------------------------------------------------------------- #
def _gelu(x: np.ndarray) -> np.ndarray:
    # exact (erf) GELU to match torch.nn.functional.gelu default
    from math import sqrt
    try:
        from scipy.special import erf
    except ImportError:  # pragma: no cover
        erf = np.vectorize(__import__("math").erf)
    return 0.5 * x * (1.0 + erf(x / sqrt(2.0)))


def fno_forward(weights: Dict[str, Any], x: np.ndarray) -> np.ndarray:
    """Numpy forward pass.  x: (B, C, ny, nx) normalised channels -> (B, out, ny, nx)."""
    cfg = weights["config"]
    B, C, H, W = x.shape
    pad, modes = cfg["padding"], cfg["modes"]
    h = np.einsum("bchw,oc->bohw", x.astype(np.float32), weights["lift_w"]) + weights["lift_b"][None, :, None, None]
    if pad > 0:
        h = np.pad(h, ((0, 0), (0, 0), (0, pad), (0, pad)))
    Hp, Wp = h.shape[-2:]
    for i in range(cfg["n_layers"]):
        x_ft = np.fft.rfft2(h, axes=(-2, -1))
        out_ft = np.zeros((B, cfg["width"], Hp, Wp // 2 + 1), dtype=np.complex64)
        w1, w2 = weights["spec%d_w1" % i], weights["spec%d_w2" % i]
        out_ft[:, :, :modes, :modes] = np.einsum("bixy,ioxy->boxy", x_ft[:, :, :modes, :modes], w1)
        out_ft[:, :, -modes:, :modes] = np.einsum("bixy,ioxy->boxy", x_ft[:, :, -modes:, :modes], w2)
        h1 = np.fft.irfft2(out_ft, s=(Hp, Wp), axes=(-2, -1)).astype(np.float32)
        h2 = np.einsum("bchw,oc->bohw", h, weights["local%d_w" % i]) + weights["local%d_b" % i][None, :, None, None]
        h = h1 + h2
        if i < cfg["n_layers"] - 1:
            h = _gelu(h)
    if pad > 0:
        h = h[..., :H, :W]
    h = np.einsum("bchw,oc->bohw", h, weights["proj1_w"]) + weights["proj1_b"][None, :, None, None]
    h = _gelu(h)
    h = np.einsum("bchw,oc->bohw", h, weights["proj2_w"]) + weights["proj2_b"][None, :, None, None]
    return h.astype(np.float32)


def grid_channels(k: np.ndarray, q: np.ndarray, h: float, t: float) -> np.ndarray:
    ny, nx = k.shape
    x = (np.arange(nx, dtype=np.float32) + 0.5) / nx
    y = (np.arange(ny, dtype=np.float32) + 0.5) / ny
    X, Y = np.meshgrid(x, y)
    out = np.empty((N_CHANNELS, ny, nx), dtype=np.float32)
    out[0] = np.log10(k)
    out[1] = np.log1p(q / 1.0e3)
    out[2] = np.log10(h)
    out[3] = t * 1.0e3
    out[4] = X
    out[5] = Y
    return out


def normalize_x(channels: np.ndarray, norm: Dict[str, Any]) -> np.ndarray:
    m = np.asarray(norm["x_mean"], dtype=np.float32)[None, :, None, None]
    s = np.asarray(norm["x_std"], dtype=np.float32)[None, :, None, None]
    return (channels - m) / s


# --------------------------------------------------------------------------- #
# Package-local glue: design -> channels -> field.
# --------------------------------------------------------------------------- #
def load_weights():
    """Read the torch-free FNO weights.

    numpy has defaulted to allow_pickle off since 1.16.3, so an .npz of plain
    arrays carries no opcode stream and needs no further guard here.
    """
    with np.load(str(WEIGHTS_PATH)) as f:
        out = {k: f[k] for k in f.files if k != "__config__"}
        out["config"] = json.loads(f["__config__"].tobytes().decode())
    return out


def design_to_fields(design):
    """Rasterise a design onto the grid: conductivity and volumetric source planes.

    Mirrors the producer's design-to-problem conversion, which is what produced every
    field this surrogate was trained on.
    """
    nx, ny, Lx, Ly = CONFIG["nx"], CONFIG["ny"], CONFIG["Lx"], CONFIG["Ly"]
    dx, dy = Lx / nx, Ly / ny
    x = (np.arange(nx) + 0.5) * dx
    y = (np.arange(ny) + 0.5) * dy
    X, Y = np.meshgrid(x, y)
    k = np.full((ny, nx), float(design["k0"]), dtype=float)
    for ins in design.get("inserts", []):
        mask = ((X >= ins["x0"]) & (X < ins["x0"] + ins["w"])
                & (Y >= ins["y0"]) & (Y < ins["y0"] + ins["hgt"]))
        k[mask] = ins["k"]
    q = np.zeros((ny, nx), dtype=float)
    for s in design.get("sources", []):
        r2 = (X - s["xc"]) ** 2 + (Y - s["yc"]) ** 2
        q += s["P"] / (2.0 * np.pi * s["sigma"] ** 2) * np.exp(-0.5 * r2 / s["sigma"] ** 2)
    return k, q


class InvalidInput(Exception):
    """An input this model will not accept.  Reported in band, never as a crash."""

    def __init__(self, code, message, field=None):
        Exception.__init__(self, message)
        self.code = code
        self.message = message
        self.field = field


def _as_number(value, name):
    """Coerce a declared numeric input to float, or refuse it by name.

    `bool` is an `int` subclass and is never a meaningful plate parameter, so it
    is refused rather than silently read as 0 or 1.
    """
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise InvalidInput("BAD_REQUEST", "%s must be a number, got %r" % (name, value), name)
    return float(value)


def _in_range(value, name):
    """Check one scalar against the manifest's declared range for that input."""
    bounds = RANGES.get(name)
    if bounds is None:
        return value
    low, high = float(bounds[0]), float(bounds[1])
    if not low <= value <= high:
        raise InvalidInput("OUT_OF_RANGE",
                           "%s=%r is outside the trained envelope [%g, %g]" % (name, value, low, high),
                           name)
    return value


def inputs_to_design(inputs):
    """Build a design object from the declared scalar inputs, or from design_json.

    Raises :class:`InvalidInput` -- not a bare ValueError -- so the caller can
    name the offending field in the protocol frame.
    """
    if not isinstance(inputs, dict):
        raise InvalidInput("BAD_REQUEST", "inputs must be a JSON object, got %s" % type(inputs).__name__)
    raw = inputs.get("design_json")
    if raw:
        try:
            design = json.loads(raw) if isinstance(raw, str) else dict(raw)
        except (TypeError, ValueError) as exc:
            raise InvalidInput("BAD_REQUEST", "design_json is not a JSON object (%s)" % exc,
                               "design_json")
        if not isinstance(design, dict):
            raise InvalidInput("BAD_REQUEST", "design_json must decode to an object", "design_json")
        for key, declared in (("k0", "k0_W_mK"), ("h", "h_W_m2K"), ("t", "t_m")):
            if key not in design:
                raise InvalidInput("MISSING_INPUT", "design_json is missing %r" % key, "design_json")
            _in_range(_as_number(design[key], "design_json.%s" % key), declared)
        design.setdefault("inserts", [])
        design.setdefault("sources", [])
        return design
    for name in REQUIRED_SCALARS:
        if inputs.get(name) is None:
            raise InvalidInput("MISSING_INPUT",
                               "required input %r is missing; supply it, or a design_json object" % name,
                               name)
        _in_range(_as_number(inputs[name], name), name)
    return {
        "k0": float(inputs["k0_W_mK"]),
        "h": float(inputs["h_W_m2K"]),
        "t": float(inputs["t_m"]),
        "inserts": [],
        "sources": [{"xc": float(inputs["source_xc_m"]), "yc": float(inputs["source_yc_m"]),
                     "sigma": float(inputs["source_sigma_m"]), "P": float(inputs["source_P_W"])}],
    }


def predict(inputs, weights):
    """One design in, one temperature-rise field plus its conformal band out."""
    design = inputs_to_design(inputs)
    k, q = design_to_fields(design)
    channels = grid_channels(k.astype(np.float32), q.astype(np.float32),
                             float(design["h"]), float(design["t"]))[None]
    z = fno_forward(weights, normalize_x(channels, NORM))
    dT = z[0, 0] * NORM["y_std"] + NORM["y_mean"]
    half = BAND_HALFWIDTH_K
    return {
        "dT": dT.astype(float).tolist(),
        "dT_lower": (dT - half).astype(float).tolist(),
        "dT_upper": (dT + half).astype(float).tolist(),
        "dT_max_K": float(dT.max()),
        "units": "K",
        "grid": [int(CONFIG["ny"]), int(CONFIG["nx"])],
    }


# --------------------------------------------------------------------------- #
# The wire format.  One frame per dispatched row; `status` is what makes a line a
# frame at all (the dispatcher's protocol-frame parser).
# --------------------------------------------------------------------------- #
def run_one(run_id, inputs, weights):
    """Validate + predict one row, returning a protocol frame (ok or error)."""
    try:
        outputs = predict(inputs, weights)
    except InvalidInput as exc:
        error = {"code": exc.code, "message": exc.message}
        if exc.field is not None:
            error["field"] = exc.field
        return {"run_id": run_id, "status": "error", "error": error}
    return {"run_id": run_id, "status": "ok", "outputs": outputs}


def write_frame(frame):
    sys.stdout.write(json.dumps(frame) + "\n")


def emit_progress(pct, message):
    """One progress event on stderr.  The dispatcher forwards these; stdout stays frames."""
    sys.stderr.write(json.dumps({"event": "progress", "pct": pct, "message": message}) + "\n")


def main() -> int:
    """Read one request, write one frame per row.  Exit 0 for any handled request.

    A nonzero exit is reserved for a failure that is not the caller's: the
    dispatcher records it as `nonzero_exit` / HTTP 502, which is the honest
    class for "this model is broken", while an in-band `status: "error"` with
    exit 0 is recorded `model_error` / HTTP 422, which is the honest class for
    "this request is outside what the model accepts".
    """
    raw = sys.stdin.read()
    try:
        request = json.loads(raw)
    except ValueError as exc:
        write_frame({"run_id": None, "status": "error",
                     "error": {"code": "BAD_REQUEST", "message": "stdin is not valid JSON (%s)" % exc}})
        return 0
    if not isinstance(request, dict):
        write_frame({"run_id": None, "status": "error",
                     "error": {"code": "BAD_REQUEST", "message": "request must be a JSON object"}})
        return 0

    run_id = request.get("run_id")
    inputs = request.get("inputs")
    if inputs is None:
        inputs = {}
    # Mode is inferred from the shape when absent, exactly as the dispatcher infers
    # it, so a bare {"inputs": {...}} request still answers.
    mode = request.get("mode") or ("batch" if isinstance(inputs, list) else "single")
    if mode not in ("single", "batch"):
        write_frame({"run_id": run_id, "status": "error",
                     "error": {"code": "BAD_REQUEST", "message": "unsupported mode %r" % mode}})
        return 0
    if (mode == "batch") != isinstance(inputs, list):
        write_frame({"run_id": run_id, "status": "error",
                     "error": {"code": "BAD_REQUEST",
                               "message": "mode %r requires inputs to be %s"
                                          % (mode, "an array" if mode == "batch" else "an object")}})
        return 0

    try:
        weights = load_weights()
    except Exception as exc:   # noqa: BLE001 - a broken package, not a bad request
        write_frame({"run_id": run_id, "status": "error",
                     "error": {"code": "INTERNAL_ERROR",
                               "message": "cannot load the packaged weights: %s: %s"
                                          % (type(exc).__name__, exc)}})
        return 1

    rows = inputs if mode == "batch" else [inputs]
    try:
        for index, row in enumerate(rows):
            emit_progress(round(100.0 * (index + 1) / max(len(rows), 1), 1),
                          "row %d/%d" % (index + 1, len(rows)) if mode == "batch" else "forward pass")
            write_frame(run_one(run_id, row, weights))
    except Exception as exc:   # noqa: BLE001 - not the caller's fault; 502 is the honest class
        write_frame({"run_id": run_id, "status": "error",
                     "error": {"code": "INTERNAL_ERROR",
                               "message": "%s: %s" % (type(exc).__name__, exc)}})
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
